#!/bin/bash

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run with root privileges. Please run it as root or using sudo." >&2
  exit 1
fi

# Backup the original sysctl.conf file
cp /etc/sysctl.conf /etc/sysctl.conf.bak

# Function to restore the original sysctl.conf file
restore_original_settings() {
  mv /etc/sysctl.conf.bak /etc/sysctl.conf
  sysctl -p /etc/sysctl.conf >/dev/null
  echo "Restored the original sysctl.conf file."
}

# Function to optimize network settings
optimize_network_settings() {
  echo ""
  echo "Modifying network settings to optimize latency and speed..."

  # Add optimized settings to sysctl.conf
  {
    echo ""
    echo "# TCP Optimization Settings"
    echo "net.ipv4.tcp_window_scaling = 1"
    echo "net.core.rmem_max = 16777216"
    echo "net.core.wmem_max = 16777216"
    echo "net.ipv4.tcp_rmem = 4096 87380 16777216"
    echo "net.ipv4.tcp_wmem = 4096 16384 16777216"
    echo "net.ipv4.tcp_low_latency = 1"
    echo "net.ipv4.tcp_slow_start_after_idle = 0"
  } >>/etc/sysctl.conf

  # Apply the new settings
  sysctl -p /etc/sysctl.conf >/dev/null

  echo ""
  echo "Network settings have been optimized successfully."
  echo ""
}

# Main script execution
clear
tput setaf 7
tput setab 4
tput bold
printf "%35s%s%-20s\n" "Network Optimization Script" 
tput sgr0

echo ""
echo "This script will optimize network settings for reducing latency and improving speed."
echo "Please note that running this script is at your own risk."
echo ""

read -p "Do you want to proceed with network optimization? [y/n]: " -e -i n answer

if [[ "$answer" = 'y' ]]; then
  optimize_network_settings
else
  echo ""
  echo "Network optimization was canceled by the user!"
  echo ""
  restore_original_settings
fi

exit 0
